### ISSUE TITLE
Issue about Collecting TRTL into my TurtleCoin Wallet

### ISSUE THREAD

**Issue by patt777** [turtlecoin/turtle-wallet-proton#150] opened 2021-06-03 23:49 UTC
Issue about collecting TRTL into my TurtleCoin Wallet;

4 June 2021 at 6:30 GMT +7
TRTLs has been mined for 8k + 854 TRTL.

Issue
BUT in the Wallet shows the error as Sync 99.xx$ already for 3-4 weeks ago (or since around 1-5 May 2021)!!! And it has collected nothing since early May 2021.

See all the info about this issue here in this link... https://drive.google.com/file/d/1Ht1Q3-C2qCrT9Jt8C_TFhswWQClYDVT6/view?usp=sharing

Please give me some advice.

Patt

**Comment by brandonlehmann** [comment] 2021-06-04 00:06
Try resyncing the wallet. https://docs.turtlecoin.lol/guides/wallets/restoring-your-wallet-from-a-specific-block-height

**Comment by ExtraHash** [comment] 2021-06-04 00:18
You could also try selecting a different node in settings if you are getting stuck at a specific height.

**Comment by patt777** [comment] 2021-06-10 00:03
Hi, I have done restore and change the node (many times) until the Turtle wallet finished its sync (5-7 days). Then I have got no TRTLs or some 7-8k TRTLs have gone from the wallet. See the pic here.
![111](https://user-images.githubusercontent.com/25258371/121444565-fa46aa80-c9b9-11eb-9fb7-3863d3c32d6a.jpg)

Please give me some advice.
Patt

**Comment by ExtraHash** [comment] 2021-06-11 01:57
I can't see the balance, so I'm not sure what the issue is here. When you restored, did you restore a block height before the first transaction in your wallet?

**Comment by patt777** [comment] 2021-06-11 02:00
Yes

**Comment by Realred123** [comment] 2021-06-16 14:29
Was this issue resolved??\

**Comment by patt777** [comment] 2021-06-16 15:20
Yes, it worked.
Thanks

ในวันที่ พ. 16 มิ.ย. 2021 21:29 น. Realred123 ***@***.***>
เขียนว่า:

**Comment by WBD33** [comment] 2021-06-19 12:14
Had coins in my wallet and sent more, never received the new coins and the existing coins are gone. Tried restoring my wallet from seed phrase but still shows my wallet empty. Help

**Comment by zpalmtree** [comment] 2021-06-19 16:20
> Had coins in my wallet and sent more, never received the new coins and the existing coins are gone. Tried restoring my wallet from seed phrase but still shows my wallet empty. Help

Your wallet probably isn't synced. Stop by our discord for assistance. http://chat.turtlecoin.lol/

**Comment by ExtraHash** [comment] 2021-06-25 01:56
Did you get this resolved in discord?

**Comment by patt777** [comment] 2021-06-25 01:57
Yes

**Closed** 2021-07-19 13:42 UTC
Labels: bug
